# Generated by Django 4.1.2 on 2022-10-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(related_name='category', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='articles.article')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='articles.category')),
            ],
        ),
    ]
