# Generated by Django 4.1.2 on 2022-10-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_category_article_article_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='checkbox_delete',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='checkbox_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article', verbose_name='СтатьЯЯ'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.category', verbose_name='Категории'),
        ),
    ]
