# Generated by Django 4.1.2 on 2022-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='group', through='school.School', to='school.teacher'),
        ),
    ]
